schema_version: 1

context:
  name: strif
  version: "3.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/strif-${{ version }}.tar.gz
  sha256: 6ea9f62d5d19013db170a7efab20b1b08153604acc94bc9d64bc18543d96c3ad

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # Upstream has strif = strif:main as script but it is a dummy and does not actually work

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - strif
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/jlevy/strif
  summary: Tiny, useful Python lib for strings and files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
